# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

glmcoef_sub <- function(grid, D_sub, X) {
    .Call(`_BHMSMAfMRI_glmcoef_sub`, grid, D_sub, X)
}

minus_ll <- function(C0, C1, C2, C3, C4, C5, subs, grid, waveletcoefmat) {
    .Call(`_BHMSMAfMRI_minus_ll`, C0, C1, C2, C3, C4, C5, subs, grid, waveletcoefmat)
}

ll <- function(C0, C1, C2, C3, C4, C5, subs, grid, waveletcoefmat) {
    .Call(`_BHMSMAfMRI_ll`, C0, C1, C2, C3, C4, C5, subs, grid, waveletcoefmat)
}

var_mle <- function(C0, C1, C2, C3, C4, C5, subs, grid, waveletcoefmat, h) {
    .Call(`_BHMSMAfMRI_var_mle`, C0, C1, C2, C3, C4, C5, subs, grid, waveletcoefmat, h)
}

LL <- function(w, l, j, n, waveletcoefmat, C0, C1, C2, C3, C4, C5) {
    .Call(`_BHMSMAfMRI_LL`, w, l, j, n, waveletcoefmat, C0, C1, C2, C3, C4, C5)
}

pklj <- function(w, l, j, i, waveletcoefmat, C4, C5) {
    .Call(`_BHMSMAfMRI_pklj`, w, l, j, i, waveletcoefmat, C4, C5)
}

pklj_bar <- function(grid, n, waveletcoefmat, C0, C1, C2, C3, C4, C5) {
    .Call(`_BHMSMAfMRI_pklj_bar`, grid, n, waveletcoefmat, C0, C1, C2, C3, C4, C5)
}

post_wavelet_coef <- function(grid, n, waveletcoefmat, pkljbar, C4, C5) {
    .Call(`_BHMSMAfMRI_post_wavelet_coef`, grid, n, waveletcoefmat, pkljbar, C4, C5)
}

set_seed <- function(seed) {
    invisible(.Call(`_BHMSMAfMRI_set_seed`, seed))
}

post_samp <- function(nsample, grid, n, waveletcoefmat, pkljbar, C4, C5, seed) {
    .Call(`_BHMSMAfMRI_post_samp`, nsample, grid, n, waveletcoefmat, pkljbar, C4, C5, seed)
}

